sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t desenvolvimento docker-image/

script:
  - docker run -t -it -v $PWD:/hello-world desenvolvimento bash -c "cd /hello-world && python preprocessor.py test"
