# Print settings

# Because of some visualization difficulties, it is necessary to write diferent files for visualization of nodes, faces, edges and volumes tags. Writing four vtk files makes the process expensive. So, if you won't need all of these files, let us know, setting 1 in the entities whose tags you want to visualize and 0 in those that you're not, so we can make the preprocessing faster ;)

# Do you want to visualize:
nodes: 0
edges: 0
faces: 0
volumes: 1
all entities: 0
